### PR TITLE
minimize Cabal.default-extensions

### PR DESCRIPTION
**Pull request by thielema**

### CODE REVIEW

**Comment by nikita-volkov** [comment]
Is that all for compatibility with GHC 7.4? I would rather not bind myself to maintaining compatibility with such old versions.

**Comment by thielema** [comment]
On Sat, 12 Jan 2019, Nikita Volkov wrote:

> Is that all for compatibility with GHC 7.4? I would rather not bind 
> myself to maintaining compatibility with such old versions.

I think it is generally a good idea to specify only extensions that are 
needed. Will certainly also help for future compatibility.

**Comment by nikita-volkov** [comment]
> I think it is generally a good idea to specify only extensions that are
needed.

This is about personal views. For instance, I have other preferences.

> Will certainly also help for future compatibility.

I can't see how that will.

Seems like unfortunately I'll have to decline this PR. Sorry.

**Comment by amigalemming** [comment]
I made a fork that uses no extensions, no custom Prelude and works with GHC back to 7.0:
https://hackage.haskell.org/package/quickcheck-transformer

**Pull request closed without merging**
